### ISSUE TITLE
Notice: Trying to get property of non-object in wp-includes/query.php

### ISSUE THREAD

**Issue by SlimJim192** [strangerstudios/pmpro-addon-packages#21]
`Notice: Trying to get property of non-object in /home/laingbuisson/public_html/wp-includes/query.php on line 4520 4522 & 4524`

Since the latest update of the core Paid Memberships Pro (1.8.10.3) this plugin is throwing this error ALOT...

Its untouched, stopped throwing once i deactivated, no customizations. Tried deactivating all other plugins... 

Also tried switching to default twenty sixteen theme!

**Comment by kimcoleman** [comment]
This is an old issue and we have not received reports of it with the latest release of Paid Memberships Pro. If you are still experiencing this issue please reopen this issue with more details.
