### ISSUE TITLE
Let users buy la carte items without buying the membership

### ISSUE THREAD

**Issue by amninders** [strangerstudios/pmpro-addon-packages#35]
It will be a good idea to let users have the option to buy the la carte item(s) without buying any membership or at least making it as an option (as upsell maybe) to buy membership alongside la carte item or just continue without buying the membership at all.
Because sometimes there can be a scenario where users just want to buy the la carte item only and not the membership(yet).

**Comment by sensemonster** [comment]
Yes, we have user scenario where the additional item is sometimes needed after registration.  The membership level must be left locked in our membership system.  It appears that this add-on-packages idea was based on modifying the membership to a different membership level.

**Comment by kimcoleman** [comment]
We may consider this in the future, but for now with PMPro v3.0+, we support multiple memberships per user in core so this is less of an urgency. Members can hold as many memberships as you want, allowing you to sell a la carte items without this feature or Addon Packages at all.
