### ISSUE TITLE
Can't update existing recurring payment info after purchasing addon package

### ISSUE THREAD

**Issue by LMNTL** [strangerstudios/pmpro-addon-packages#39]
If a member that already has a membership level with a recurring payment, then checks out for an add on package, they can no longer update payment information on the billing page. Only affects gateways where billing updates/checkouts are processed onsite. 

Steps to recreate (using Stripe): 
1. Create a membership level with a recurring payment
2. Checkout for that membership level
3. Go to membership billing page, see option to update payment/address info
4. Create an addon page restricted to the membership level from step 1
5. While still logged in, checkout for addon page from previous step
6. Go to membership billing page, see "This subscription is not recurring. So you don't need to update your billing information." message, no option to update payment/address info

**Comment by ihsankhan99** [comment]
> I am able to recreate this issue be it for an imported member or a member that went through pmpro checkout.
> 
> For moderators only: https://www.paidmembershipspro.com/forums/topic/user-cant-update-payment-method-if-imported-from-previous-site/

this link is not working,

**Comment by ihsankhan99** [comment]
> This continues to be a problem for site owners.

Hello Kimwite, yes we are facing the problem, I am searching for a solution, I am working on my client's website, and she has paid membership pro premium version, I also submit a ticket about this issue, and in discussion with Micheal Beil. 

can you provide and solution?

**Comment by kimcoleman** [comment]
This is resolved in PMPro v3.0+ and higher.
