### ISSUE TITLE
Show expiration date for addon packages to users

### ISSUE THREAD

**Issue by dparker1005** [strangerstudios/pmpro-addon-packages#43]
Right now, an expiration date can be set for addon packages by setting the `PMPROAP_EXP_DAYS` constant; however, this is not communicated to the users. It would be nice to give them a way to see their expiration date so that they do not lose access without warning.

User ticket (admins only): https://www.paidmembershipspro.com/forums/topic/re-pmproap_exp_days/#post-275518

**Comment by kimcoleman** [comment]
Added in https://github.com/strangerstudios/pmpro-addon-packages/pull/65
