### ISSUE TITLE
working only for Standard post format

### ISSUE THREAD

**Issue by sirol81** [strangerstudios/pmpro-addon-packages#47]
if I create a Standard post format, it works ok.
But if I create a Video post format for example, it gets overridden.

Is there a hook or filter where I can add custom logic to enable Video Post format to be restricted?

thanks

**Comment by bethgee** [comment]
Did you ever find a solution for this? I am trying to integrate PMP with an Events plugin and am trying to get around needing to create a Membership Level for each class to allow single class access...

Thanks,
Beth

**Comment by sirol81** [comment]
Not a real solution, but as a workaround I copy/pasted the logic found in this PMP plugin and put in a child theme php where it writes the html. This way I can protect the Video post format too, but I hopen in a hook or something to do that

**Comment by bethgee** [comment]
Sorry, do you mind sharing the logic you copy-pasted? I am pretty new to JS and JQuery and get confused. Is it the part referenced on https://github.com/strangerstudios/pmpro-addon-packages/issues/45 ?

Did you just make this $post_type = "page, 'CPT'"; ? Or would it be $post_type = array('post', 'page', 'CPT');  ?

Really appreciate your responding!!

**Comment by sirol81** [comment]
I took this function from the plugin:
`function pmproap_pmpro_text_filter( $text ) {`
and added it to my funtion.php from my child theme, renamed it and called when needed to visualize my video post format content

**Comment by bethgee** [comment]
OK, will have a look in a bit, thank you!

**Comment by andrewlimaza** [comment]
You may use the following filter to add functionality of Addon Packages to any post type needed - https://github.com/strangerstudios/pmpro-addon-packages/blob/dev/pmpro-addon-packages.php#L103

Please note that Github is used for bug reporting. For any support related questions to this product, please reach out to www.paidmembershipspro.com

Thanks!

**Comment by bethgee** [comment]
For future, if anyone needs this info, I needed to add the Custom Post Type Add On as well as the Addon Packages Add On to get the Addon Packages box to show on my custom posts!!

**Comment by bethgee** [comment]
(also, I had reached out to support, but it has taken a week of back and forth to figure out I needed this extra add on...! So I thought it was worth asking here too just in case)
