### ISSUE TITLE
BUG: Overwrites the 'billing' amount on the account page.

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-addon-packages#48]
When purchasing an Addon Package, this shows the purchased value of the Addon Package under 'billing' on the account page instead of the original member's price/subscription amount.

Steps to recreate:

- Signup for a membership level, let's say $1 a month.
- Create an Addon Package post that is $5 to purchase.
- Purchase the Addon Package.
- Navigate to your account page, view the current membership level billing table and pricing shown is $5 instead of $1.

In this image below, the Addon Post was $10 to gain access, and my test account had a previously set $1 per month membership. After purchasing access, it shows as $10.
![image](https://user-images.githubusercontent.com/12629136/102196276-5bd50300-3ec8-11eb-908c-65ba5119c2b6.png)

**Comment by MaryOJob** [comment]
Moderators Only: #460492

**Comment by kimcoleman** [comment]
This should be fixed as of PMPro v3.0 + this PR: https://github.com/strangerstudios/pmpro-addon-packages/pull/65
