### ISSUE TITLE
Expiration shows January 1, 1979

### ISSUE THREAD

**Issue by theogodson** [strangerstudios/pmpro-addon-packages#49]
I've been trying to fix it, I don't know what else to do

**Comment by mircobabini** [comment]
Check this up: https://github.com/strangerstudios/pmpro-addon-packages/blob/c097328c2598cb99e9a9c47bb24e87e93a52d397/pmpro-addon-packages.php#L29-L34

Did you set that `PMPROAP_EXP_DAYS` constant in your wp-config.php?

**Comment by kimcoleman** [comment]
We are not hearing current reports of this issue. I am closing this ticket and will revisit if new reports of this issue arise.
