### ISSUE TITLE
Is it possible to restrict access to Addon Packages to finish on a set date?!

### ISSUE THREAD

**Issue by bethgee** [strangerstudios/pmpro-addon-packages#50]
I have added this and the Custom Post Type Addon to my clients site in order to sell her classes both in a membership and individually. However, we would like to restrict access to those purchasing an individual class to only have access to the live class, not after it's date. Is this possible??

Help please!

**Comment by airplanenoise** [comment]
Try refreshing your permalinks?
--
Kaz

**Comment by bethgee** [comment]
> Try refreshing your permalinks? -- Kaz

Apologies, I have changed the question. In the end, as long as I leave the CPT addon as deactivated, the pages show. So I can simply activate it when adding new events, then disable it - the pricing still appears on the front end even though the options in the back do not, so I can live with that for now!
