### ISSUE TITLE
Invoices and Orders show incorrect information.

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-addon-packages#57]
Invoices display incorrect information when using Addon Package

**There are 2 ways to view order**

**User Account Page - under INVOICES**
When clicking on the invoice date, all invoices show all previously purchased packages, even if a package was not purchased.
ALL invoices, even past invoices.
<img width="862" alt="Screen Shot 2022-09-30 at 2 13 51 PM" src="https://user-images.githubusercontent.com/8083630/193333778-57447eda-9169-43e0-827f-93d481743e76.png">

**From Admin area:**
_Email Order from Order List_
This invoice shows only the Level Name and nothing about the Add On.
The invoice should show the Addon Package title, not the Level Name

<img width="691" alt="Screen Shot 2022-09-30 at 2 15 26 PM" src="https://user-images.githubusercontent.com/8083630/193333832-993e0cb2-de2f-4086-a4a3-1f914a3732bd.png">

**Comment by MaryOJob** [comment]
Moderators Only: #460617

**Comment by kimcoleman** [comment]
This is resolved #65  and will ship in v3.1
