### ISSUE TITLE
Payment did not unlock Content

### ISSUE THREAD

**Issue by GWDInc** [strangerstudios/pmpro-addon-packages#6]
We are using this plugin along with Paid Memberships Pro on a site offering online Continuing Ed courses. We have the PMPro Addon Packages plugin set on our course description page that members can click to purchase. We made the site live yesterday and I had someone try to purchase a course to see if everything was working. This is the email I received from her.
"I clicked on the purchase button and was able to link to paypal and go through those steps.  I got an email from paypal in my personal account and an email to PTA Only stating that we received a payment. 
After paying, there was a transaction number and a link to return to PTAonly.com.  I did that and was directed to the welcome page for new members (free membership).  
I did not gain access to the course materials however."

Is there something else I need to do in the programming or do I need to set up a special landing page that will key/alert the code of the payment?

Thanks for your help.
Pam

**Comment by contemplate** [comment]
Hi Guys.  I created a work around in this Pull Request:
https://github.com/strangerstudios/pmpro-addon-packages/pull/24

Basically whenever the Order gets updated to a status of "success" from PayPal Standard then it reads the Order Note to grab the addon package and give the user access.   I've tested this in a live case scenario and it works well.  Hope it can be included in the core here.
