### ISSUE TITLE
PMPro addon-packages-master confirmation page issue

### ISSUE THREAD

**Issue by bkappus** [strangerstudios/pmpro-addon-packages#8]
I think there is a bug in the
/wp-content/plugins/pmpro-addon-packages-master/pmpro-addon-packages.php file with respect to:
- After checking out, they are taken to a new confirmation page or the PMPro confirmation page with extra info.

I am unable to find where to "create" the new confirmation page. Right now, the confirmation page is pulling the "message" from my initial membership confirmation and it is adding the sentence that my "add-on" is available to be clicked.

I need to have a clean confirmation page that removes the original confirmation message and only leaves me the sentence that my "add-on" is available.

I tried to modify this to remove the "pmpro_confirmation_message" but I received an error.

add_filter("pmpro_confirmation_message","pmproap_pmpro_confirmation_message");

Please let me know the proper way to A) suppress the original confirmation message or B) create the new confirmation message for the add-on like it states in the "readme.txt" file.

Thanks very much.. This is sorta urgent.

Brian

https://wordpress.org/plugins/paid-memberships-pro/

**Comment by kimcoleman** [comment]
This method outlines how to redirect to a unique confirmation page based on membership level. This could be modified to use the `pmproap_hasAccess` function and redirect based on the post ID and current_user: https://www.paidmembershipspro.com/set-up-unique-membership-confirmation-pages-based-on-level/
